rust:
    - changed-files:
          - any-glob-to-any-file: "**/*.rs"

javascript:
    - changed-files:
          - any-glob-to-any-file:
                - "**/*.js"
                - "**/*.jsx"
                - "**/*.ts"
                - "**/*.tsx"
                - "**/*.mjs"
                - "**/*.cjs"

ui:
    - changed-files:
          - any-glob-to-any-file: "**/*.vue"

configuration:
    - changed-files:
          - any-glob-to-any-file:
                - "vite.config.ts"
                - "vitest.config.ts"
                - "tsconfig.*.json"
                - "tauri.conf.json"

dependencies:
    - changed-files:
          - any-glob-to-any-file:
                - "package.json"
                - "yarn.lock"
                - "pnpm-lock.yaml"
                - "Cargo.toml"
                - "Cargo.lock"

tests:
    - changed-files:
          - any-glob-to-any-file: "src/tests/**/*"

feature:
    - head-branch: ["^feat(/.*|$)", "^feature(/.*|$)"]

hotfix:
    - head-branch: ["^hotfix(/.*|$)", "^fix(/.*|$)"]
