name: "Frontend Tests"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-frontend-test
    cancel-in-progress: true

on:
    workflow_call:
    pull_request:
    workflow_dispatch:

permissions:
    contents: read
    actions: read

jobs:
    vitest:
        name: Run Vitest Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24

            - name: Enable Corepack
              run: corepack enable

            - name: Use Yarn 2
              run: corepack prepare yarn@2.4.3 --activate

            - name: Install dependencies
              run: yarn install --immutable

            - name: Run Vitest
              run: yarn vitest run

            - name: It actually builds
              run: yarn build
